mail: add neomutt+notmuch+mbsync+msmtp configuration
This is probably the usual neomutt+notmuch setup, with one notable
exception: I don't use tags at all (at least no tags that are not
automatically deduced from and synced to the maildir), but still use
folders instead. Why? Because synchronizing notmuch tags seems to be
rather finnicky, and I also do not want to degrade the experience over
IMAP. The setup I have right now can be replaced by a different one
without losing any data, this is no longer true when embracing the
notmuch tags. Maybe some day something like JMAP gets popular enough
that you can sync notmuch tags with it.
What is notmuch good for without tags then? Well, it is still a fast
search engine, but most importantly it can both implicitly and
explicitly assemble threads from messages in different folders - like
the Inbox and Sent. Yeah, this should be a feature of the MUA itself,
but for some reason the only client I know supporting this natively is
an obscure Android App called "Fair Email"…